public enum PlayerEffect
{
    ATTACK,
    DEFEND,
    HEAL,
    DRAW,
    GAIN_ENERGY,
    MODIFY_CARD_DRAW_PER_TURN,
    MODIFY_ENERGY_PER_TURN,
    SELF_DAMAGE,
    DAMAGE_PER_0_COST_CARD_IN_HAND,
    DAMAGE_PER_CARD_IN_HAND,
    REMOVE_ENEMY_ARMOR,
    HYPER_PULSE
}