public enum EventName
{
    ON_PLAYER_GAIN_BLOCK,
    ON_PLAYER_PLAY_CARD,
    ON_PLAYER_END_TURN,
    ON_PLAYER_START_TURN,
    ON_PLAYER_DEAL_DAMAGE,
    ON_PLAYER_DRAW_CARD,
    ON_PLAYER_EXHAUST_CARD,
    ON_PLAYER_HEAL,
    ON_COMBAT_END
}